"""initial migration

Revision ID: f3f5016370a0
Revises:
Create Date: 2025-12-24 09:51:25.437615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3f5016370a0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urllinks",
        sa.Column("original_url", sa.String(), nullable=False),
        sa.Column("short_code", sa.String(length=25), nullable=False),
        sa.Column("click_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время создания записи",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_urllinks")),
        sa.UniqueConstraint("short_code", name=op.f("uq_urllinks_short_code")),
    )
    op.create_index(op.f("ix_urllinks_id"), "urllinks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urllinks_id"), table_name="urllinks")
    op.drop_table("urllinks")
    # ### end Alembic commands ###
